SCRUM-7-navigation-bar
goislimat/marquei-web pull request #6
Opened 2024-01-26 02:14 UTC by RafaRafa26

2024-01-30 18:26 UTC, goislimat requested changes

2024-01-30 18:26 UTC, goislimat commented on src/app/page.tsx
> +    <div className="navigation-bar">
Vamos usar uma <section> aqui ao invés da <div> pra sinalizar com mais clareza que se trata de uma seção de atalhos.

2024-01-30 18:26 UTC, goislimat commented on src/app/page.tsx
> +      </div>
Vamos adicionar botões em volta desses svgs pra sinalizar que eles devem ter ações. Por mais que alguns possas se tornar links mais pra frente, pelo menos a gente tem um indicativo em html que esses elementos tem interação com o usuário.

```suggestion
      <div>
      <button>
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <circle cx="11" cy="11" r="7" stroke="#33363F" stroke-width="2" />
          <path
            d="M20 20L17 17"
            stroke="#33363F"
            stroke-width="2"
            stroke-linecap="round"
          />
        </svg>
        </button>
      </div>
```

2024-01-30 18:29 UTC, goislimat commented
Teria como adicionar um screenshot do resultado atual na descrição do pull request? Assim a gente consegue ver mais fácil como tá o resultado atual sem ter que baixar a branch e rodar localmente.

2024-01-30 18:37 UTC, RafaRafa26 commented on src/app/page.tsx
> +    <div className="navigation-bar">
Não entendi qual alteração preciso fazer, pode explicar melhor por favor?

2024-01-30 18:40 UTC, goislimat commented on src/app/page.tsx
> +    <div className="navigation-bar">
Esqueci de colocar uns backticks e bugou o comentário. Eu editei e deve estar certo agora.

2024-01-30 18:40 UTC, goislimat commented on src/app/page.tsx
> +    <div className="navigation-bar">
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

2024-01-30 18:48 UTC, RafaRafa26 commented on src/app/page.tsx
> +    <div className="navigation-bar">
Sim, agora entendi, fiz a alteração.

2024-01-30 19:51 UTC, goislimat commented on src/app/page.tsx
> +    <div className="navigation-bar">
@RafaRafa26 faz o commit e o push das alterações pra eu poder revisar elas, por favor.

2024-01-31 15:41 UTC, goislimat approved these changes

2024-01-31 16:16 UTC, merged