Add header Marquei
goislimat/marquei-web pull request #7
Opened 2024-01-30 17:35 UTC by JaqAmaral

2024-01-30 18:36 UTC, goislimat requested changes
Adiciona um print da tela com o resultado desse layout pra gente poder revisar o PR sem ter que rodar a branch localmente.

2024-01-30 18:36 UTC, goislimat commented on src/app/page.tsx
> +        <h2 className="show">Nome</h2>
```suggestion
        <span className="show">Nome</span>
```

Acho que aqui a gente não deveria usar headers nos nomes. Eles não tem tanta importância assim pro conteúdo e nem representam seções ou itens. Então eu usaria apenas simples spans aqui.

2024-01-30 18:36 UTC, goislimat commented on src/app/style.css
> +};*/
Se não for usar remove. Tenta evitar subir código comentado pra produção.

PS: pode subir comentários só não suba código comentado.

2024-01-30 18:36 UTC, goislimat commented on src/app/style.css
> +header {
Coloque uma classe nesse header. Assim se usarmos outro header no futuro ele não vai ter o estilo afetado sem querer por esse css aqui.

2024-01-30 18:36 UTC, goislimat commented on src/app/style.css
> +  font-family: "Acme", sans-serif;
Vamos tentar manter só fonte inter, pelo menos até a gente bater o martelo nas definições do layout.

2024-01-30 18:36 UTC, goislimat commented on src/app/LOGO_MARQUEI.jpeg
Exporta essa imagem como png. Seria massa se a gente conseguisse ter essa imagem sem fundo salva. Mas esse não é obrigatório já que a gente ainda precisa decidir certinho qual layout vai entrar.

2024-01-30 18:38 UTC, goislimat commented on src/app/style.css
> +  float: right;
Tente usar `display: flex` no pai e alinhar os elementos os elementos com `justify-content`. A gente não usa mais float pq ele buga muito e tem o comportamento bem imprevisível.

2024-01-31 19:14 UTC, JaqAmaral commented on src/app/page.tsx
> +        <h2 className="show">Nome</h2>
Alterações feitas

2024-01-31 19:17 UTC, JaqAmaral commented on src/app/LOGO_MARQUEI.jpeg
![LOGO_MARQUEI](https://github.com/goislimat/marquei-web/assets/133810168/f6096e93-b89e-45d6-b1c1-0c6d1a7a8533)

2024-01-31 19:32 UTC, JaqAmaral commented on src/app/page.tsx
> +        <h2 className="show">Nome</h2>
![image](https://github.com/goislimat/marquei-web/assets/133810168/a326b7b8-ef47-4915-ada0-2988111c6d85)

2024-01-31 19:35 UTC, JaqAmaral commented on src/app/page.tsx
> +        <h2 className="show">Nome</h2>
![Captura de tela 2024-01-31 163204](https://github.com/goislimat/marquei-web/assets/133810168/d2d53128-5bf4-4160-9bc8-2537a9886e01)

2024-01-31 19:37 UTC, JaqAmaral commented on src/app/page.tsx
> +        <h2 className="show">Nome</h2>
![Captura de tela 2024-01-31 163204 1](https://github.com/goislimat/marquei-web/assets/133810168/3a83e025-4fc4-4677-82bb-ab463cbb0b63)

2024-02-01 18:26 UTC, goislimat reviewed
Eu creio que essas duas alterações podem chegar mais perto do resultado esperado pra essa página.

2024-02-01 18:26 UTC, goislimat commented on src/app/page.tsx
> +      </div>
Vou sugerir aqui algumas alterações pra dar uma melhorada na hierarquia do conteúdo aqui.

```suggestion
      <header className="page-header">
        <div className="header-image-container">
          <Image src={imageLogoMarquei} alt="The logo Marquei" />
        </div>

        <span className="header-user-tag">Nome</span>
      </div>
```

2024-02-01 18:26 UTC, goislimat commented on src/app/style.css
> +}
Aqui a gente vai mudar um pouquinho o css pra bater com a sugestão de cima.

```suggestion
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  padding: 24px;
}

.header-user-tag {
  font-size: 25px;
}
```

2024-02-05 14:55 UTC, JaqAmaral reviewed
Alterações os códigos sugeridos

2024-02-05 23:25 UTC, goislimat approved these changes

2024-02-05 23:26 UTC, merged